'use client'
import {useState} from 'react'
const Arrow=()=> <span aria-hidden>↗</span>
export default function Home(){
 const [sent,setSent]=useState(false)
 function submit(e){e.preventDefault();setSent(true)}
 return <main>
  <nav className="nav wrap"><a className="logo" href="#top"><span>ÖNAL</span><small>FİLO</small></a><div className="links"><a href="#hizmetler">Hizmetler</a><a href="#kurumsal">Kurumsal</a><a href="#surec">Nasıl Çalışıyoruz</a></div><a className="navCta" href="#teklif">Teklif Talebi <Arrow/></a></nav>
  <section className="hero" id="top"><div className="wrap heroGrid"><div className="heroCopy"><div className="eyebrow">ANKARA · KURUMSAL FİLO</div><h1>Kurumsal filonuzu<br/>tek noktadan yönetin.</h1><p>Şirketlerin uzun dönem araç ihtiyaçları için tedarikten operasyon yönetimine kadar uçtan uca filo hizmetleri.</p><div className="actions"><a className="primary" href="#teklif">Teklif talep edin <Arrow/></a><a className="textLink" href="#hizmetler">Hizmetleri inceleyin ↓</a></div></div><div className="heroVisual"><div className="road"></div><div className="fleet"><div className="car c1">Ö</div><div className="car c2">Ö</div><div className="car c3">Ö</div></div><div className="visualLabel"><b>ÖNAL FİLO</b><span>Kurumsal araç filoları için uzun dönem çözümler</span></div></div></div></section>
  <section className="statement"><div className="wrap"><p className="sectionNo">01 / YAKLAŞIM</p><h2>Araç ihtiyacını yalnızca karşılamıyoruz.<br/><span>Filoyu bir bütün olarak ele alıyoruz.</span></h2><div className="statementGrid"><p>İhtiyaç analizi, araç tedariği, sözleşme dönemi ve operasyon süreçlerini şirketinizin yapısına göre planlıyoruz.</p><p>Tek bir araçtan ziyade, filonun tamamında süreklilik ve öngörülebilirlik sağlayan uzun dönemli iş ortaklığına odaklanıyoruz.</p></div></div></section>
  <section className="services wrap" id="hizmetler"><p className="sectionNo">02 / HİZMETLER</p><div className="serviceHead"><h2>Filo operasyonunun<br/>temel ihtiyaçları.</h2><p>Her şirketin kullanım modeli farklı. Filo yapısını araç sayısı, segment, süre ve operasyonel gereksinimlere göre oluşturuyoruz.</p></div><div className="cards">{[['01','Uzun Dönem Filo Kiralama','Kurumsal ihtiyaçlara göre planlanan uzun dönem araç kiralama modelleri.'],['02','Araç Tedariği','Farklı segmentlerdeki araçların filo planınıza uygun şekilde tedariği.'],['03','Filo Operasyonu','Filo kullanım süresince operasyonel süreçlerin merkezi şekilde takibi.'],['04','Filo Yenileme','Değişen ihtiyaçlara ve sözleşme dönemlerine göre filonun planlı yenilenmesi.']].map(x=><article className="card" key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p><Arrow/></article>)}</div></section>
  <section className="dark" id="kurumsal"><div className="wrap darkGrid"><div><p className="sectionNo light">03 / ÖNAL FİLO</p><h2>İşletmeler için<br/>kurulmuş bir filo yapısı.</h2></div><div className="darkCopy"><p>Önal Filo, Ankara merkezli olarak kurumsal müşterilerin uzun dönem araç ve filo ihtiyaçlarına hizmet verir.</p><p>Çalışma modelimizin merkezinde hızlı iletişim, ihtiyaca uygun planlama ve filonun operasyon boyunca sürdürülebilir şekilde yönetilmesi bulunur.</p><div className="location">ANKARA <span>→</span> TÜRKİYE GENELİ</div></div></div></section>
  <section className="process wrap" id="surec"><p className="sectionNo">04 / SÜREÇ</p><h2>İhtiyaçtan teslimata.</h2><div className="steps">{[['01','İhtiyacı belirliyoruz','Araç sayısı, segmentler, kullanım süresi ve operasyonel beklentileri birlikte değerlendiriyoruz.'],['02','Filoyu planlıyoruz','Şirketiniz için uygun araç ve sözleşme yapısını oluşturuyoruz.'],['03','Araçları tedarik ediyoruz','Planlanan filonun tedarik ve teslim süreçlerini yönetiyoruz.'],['04','Operasyonu sürdürüyoruz','Kiralama dönemi boyunca filo süreçlerini tek merkezden takip ediyoruz.']].map(x=><div className="step" key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></section>
  <section className="quote" id="teklif"><div className="wrap quoteGrid"><div><p className="sectionNo">05 / TEKLİF</p><h2>Yeni filonuzu<br/>konuşalım.</h2><p className="quoteIntro">İhtiyacınızı birkaç bilgiyle paylaşın. Ekibimiz şirketinize uygun filo yapısı için sizinle iletişime geçsin.</p></div><form onSubmit={submit}>{sent?<div className="success"><b>Talebiniz alındı.</b><p>Bu demo formudur. Canlıya almadan önce formu e-posta/CRM sisteminize bağlayabiliriz.</p></div>:<><label>Ad Soyad<input required placeholder="Adınız ve soyadınız"/></label><label>Şirket<input required placeholder="Şirket adı"/></label><div className="two"><label>E-posta<input required type="email" placeholder="ornek@sirket.com"/></label><label>Telefon<input placeholder="+90"/></label></div><label>Yaklaşık araç ihtiyacı<select defaultValue=""><option value="" disabled>Seçiniz</option><option>10–25 araç</option><option>26–50 araç</option><option>51–100 araç</option><option>100+ araç</option></select></label><label>Not<textarea rows="3" placeholder="İhtiyacınızla ilgili kısa bilgi"></textarea></label><button>Teklif talebi gönder <Arrow/></button></>}</form></div></section>
  <footer><div className="wrap footerGrid"><div className="logo footerLogo"><span>ÖNAL</span><small>FİLO</small></div><div><b>Önal Filo</b><p>Kurumsal Filo Kiralama<br/>Ankara, Türkiye</p></div><div><b>Menü</b><a href="#hizmetler">Hizmetler</a><a href="#kurumsal">Kurumsal</a><a href="#teklif">Teklif Talebi</a></div><div><b>İletişim</b><p>Telefon ve e-posta bilgileri<br/>yayın öncesi eklenecek.</p></div></div><div className="wrap copyright">© {new Date().getFullYear()} Önal Filo <span>Kurumsal Filo Çözümleri</span></div></footer>
 </main>
}
